-- Generated by Copilot per prompt: GO-AIBOB (GBOB) — GentleOmegaAI
-- Database Migration: GBOB Scraping Pipeline
-- Version: 1.0.0
-- Target: PostgreSQL 14+

-- ============================================
-- TABLE: gob_sites
-- Purpose: Store scraped website data with enrichment
-- ============================================

CREATE TABLE IF NOT EXISTS gob_sites (
    id BIGSERIAL PRIMARY KEY,
    
    -- URL Information
    url TEXT NOT NULL UNIQUE,
    canonical TEXT,
    domain TEXT GENERATED ALWAYS AS (
        CASE 
            WHEN url ~ '^https?://' THEN 
                regexp_replace(regexp_replace(url, '^https?://([^/]+).*$', '\1'), '^www\.', '')
            ELSE NULL
        END
    ) STORED,
    
    -- Page Metadata
    title TEXT,
    h1 TEXT,
    meta_description TEXT,
    first_paragraph TEXT,
    
    -- Contact Information
    emails JSONB DEFAULT '[]'::jsonb,
    phone_numbers JSONB DEFAULT '[]'::jsonb,
    
    -- Link Analysis
    links_count INTEGER DEFAULT 0,
    links_sample JSONB DEFAULT '[]'::jsonb,
    internal_links_count INTEGER DEFAULT 0,
    external_links_count INTEGER DEFAULT 0,
    
    -- Content Storage
    raw_html TEXT,
    html_snapshot TEXT, -- Truncated to MAX_HTML_SNAPSHOT_LENGTH
    html_length INTEGER,
    
    -- Scoring & Enrichment
    spam_score INTEGER DEFAULT 0 CHECK (spam_score >= 0 AND spam_score <= 100),
    backlink_value NUMERIC(10,2) DEFAULT 0.00,
    domain_authority INTEGER CHECK (domain_authority >= 0 AND domain_authority <= 100),
    guest_post_detected BOOLEAN DEFAULT FALSE,
    
    -- HuggingFace Enrichment
    category TEXT DEFAULT 'Other',
    language TEXT,
    summary TEXT,
    hf_enrichment JSONB DEFAULT '{}'::jsonb,
    hf_enriched_at TIMESTAMP WITH TIME ZONE,
    
    -- Status & Metadata
    status VARCHAR(50) DEFAULT 'new' CHECK (status IN ('new', 'queued', 'scraping', 'scraped', 'enriching', 'enriched', 'error', 'blocked', 'timeout')),
    error_message TEXT,
    retry_count INTEGER DEFAULT 0,
    
    -- Timestamps
    scraped_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Indexing hints
    CONSTRAINT valid_email_json CHECK (jsonb_typeof(emails) = 'array'),
    CONSTRAINT valid_links_json CHECK (jsonb_typeof(links_sample) = 'array')
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_gob_sites_domain ON gob_sites(domain);
CREATE INDEX IF NOT EXISTS idx_gob_sites_status ON gob_sites(status);
CREATE INDEX IF NOT EXISTS idx_gob_sites_category ON gob_sites(category);
CREATE INDEX IF NOT EXISTS idx_gob_sites_scraped_at ON gob_sites(scraped_at DESC);
CREATE INDEX IF NOT EXISTS idx_gob_sites_backlink_value ON gob_sites(backlink_value DESC);
CREATE INDEX IF NOT EXISTS idx_gob_sites_spam_score ON gob_sites(spam_score);
CREATE INDEX IF NOT EXISTS idx_gob_sites_guest_post ON gob_sites(guest_post_detected) WHERE guest_post_detected = TRUE;
CREATE INDEX IF NOT EXISTS idx_gob_sites_emails_count ON gob_sites((jsonb_array_length(emails))) WHERE jsonb_array_length(emails) > 0;

-- Full-text search index
CREATE INDEX IF NOT EXISTS idx_gob_sites_search ON gob_sites USING gin(to_tsvector('english', coalesce(title, '') || ' ' || coalesce(meta_description, '')));

-- ============================================
-- TABLE: gob_orders
-- Purpose: Store backlink purchase orders
-- ============================================

CREATE TABLE IF NOT EXISTS gob_orders (
    id BIGSERIAL PRIMARY KEY,
    
    -- Site Reference
    site_id BIGINT NOT NULL REFERENCES gob_sites(id) ON DELETE CASCADE,
    site_url TEXT NOT NULL,
    
    -- Buyer Information
    buyer_name VARCHAR(255) NOT NULL,
    buyer_email VARCHAR(255) NOT NULL,
    buyer_phone VARCHAR(50),
    buyer_company VARCHAR(255),
    
    -- Order Details
    keywords TEXT[], -- Target keywords for guest post
    content_type VARCHAR(100) DEFAULT 'guest_post' CHECK (content_type IN ('guest_post', 'banner_ad', 'sponsored_article', 'link_insertion')),
    target_url TEXT NOT NULL, -- Buyer's URL to link to
    
    -- Pricing
    price_estimate NUMERIC(10,2) NOT NULL,
    price_final NUMERIC(10,2),
    currency VARCHAR(3) DEFAULT 'USD',
    
    -- Payment Status
    status VARCHAR(50) DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'processing', 'published', 'completed', 'cancelled', 'refunded')),
    payment_method VARCHAR(50) DEFAULT 'stripe',
    payment_intent_id VARCHAR(255), -- Stripe payment intent
    invoice_id VARCHAR(100) UNIQUE,
    
    -- Order Metadata
    notes TEXT,
    admin_notes TEXT,
    estimated_delivery_days INTEGER DEFAULT 14,
    delivered_at TIMESTAMP WITH TIME ZONE,
    
    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_gob_orders_site_id ON gob_orders(site_id);
CREATE INDEX IF NOT EXISTS idx_gob_orders_buyer_email ON gob_orders(buyer_email);
CREATE INDEX IF NOT EXISTS idx_gob_orders_status ON gob_orders(status);
CREATE INDEX IF NOT EXISTS idx_gob_orders_created_at ON gob_orders(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_gob_orders_invoice_id ON gob_orders(invoice_id);

-- ============================================
-- TABLE: gob_enrichment_queue
-- Purpose: Track HuggingFace enrichment jobs
-- ============================================

CREATE TABLE IF NOT EXISTS gob_enrichment_queue (
    id BIGSERIAL PRIMARY KEY,
    site_id BIGINT NOT NULL REFERENCES gob_sites(id) ON DELETE CASCADE,
    job_type VARCHAR(50) DEFAULT 'full_enrichment' CHECK (job_type IN ('full_enrichment', 'classification', 'summarization', 'language_detection')),
    status VARCHAR(50) DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'completed', 'failed', 'rate_limited')),
    retry_count INTEGER DEFAULT 0,
    error_message TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    processed_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_gob_enrichment_site_id ON gob_enrichment_queue(site_id);
CREATE INDEX IF NOT EXISTS idx_gob_enrichment_status ON gob_enrichment_queue(status);

-- ============================================
-- TABLE: gob_scraping_stats
-- Purpose: Track scraping performance and costs
-- ============================================

CREATE TABLE IF NOT EXISTS gob_scraping_stats (
    id BIGSERIAL PRIMARY KEY,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    
    -- Counts
    total_scraped INTEGER DEFAULT 0,
    successful INTEGER DEFAULT 0,
    failed INTEGER DEFAULT 0,
    blocked INTEGER DEFAULT 0,
    
    -- Performance
    avg_scrape_time_ms INTEGER,
    total_pages_processed INTEGER DEFAULT 0,
    
    -- Enrichment
    total_enriched INTEGER DEFAULT 0,
    hf_api_calls INTEGER DEFAULT 0,
    hf_errors INTEGER DEFAULT 0,
    
    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    UNIQUE(date)
);

-- ============================================
-- TRIGGERS: Auto-update timestamps
-- ============================================

CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER gob_sites_updated_at
    BEFORE UPDATE ON gob_sites
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER gob_orders_updated_at
    BEFORE UPDATE ON gob_orders
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER gob_scraping_stats_updated_at
    BEFORE UPDATE ON gob_scraping_stats
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at();

-- ============================================
-- VIEWS: Convenient queries
-- ============================================

-- High-value sites with emails
CREATE OR REPLACE VIEW gob_high_value_sites AS
SELECT 
    id,
    url,
    domain,
    title,
    category,
    backlink_value,
    spam_score,
    jsonb_array_length(emails) as email_count,
    links_count,
    guest_post_detected,
    scraped_at
FROM gob_sites
WHERE 
    status = 'enriched'
    AND backlink_value > 10
    AND spam_score < 30
    AND jsonb_array_length(emails) > 0
ORDER BY backlink_value DESC, spam_score ASC;

-- Recent orders summary
CREATE OR REPLACE VIEW gob_orders_summary AS
SELECT 
    o.id,
    o.invoice_id,
    o.site_url,
    s.domain,
    s.category,
    o.buyer_email,
    o.price_final,
    o.status,
    o.created_at,
    o.delivered_at
FROM gob_orders o
LEFT JOIN gob_sites s ON o.site_id = s.id
ORDER BY o.created_at DESC;

-- ============================================
-- FUNCTIONS: Helper utilities
-- ============================================

-- Generate invoice ID
CREATE OR REPLACE FUNCTION generate_invoice_id()
RETURNS TEXT AS $$
BEGIN
    RETURN 'INV-' || TO_CHAR(NOW(), 'YYYYMMDD') || '-' || LPAD(FLOOR(RANDOM() * 99999)::TEXT, 5, '0');
END;
$$ LANGUAGE plpgsql;

-- Calculate backlink price estimate
CREATE OR REPLACE FUNCTION calculate_backlink_price(site_id_param BIGINT)
RETURNS NUMERIC AS $$
DECLARE
    base_price NUMERIC := 50.00;
    site_data RECORD;
    calculated_price NUMERIC;
BEGIN
    SELECT 
        backlink_value,
        spam_score,
        domain_authority,
        guest_post_detected,
        category
    INTO site_data
    FROM gob_sites
    WHERE id = site_id_param;
    
    IF NOT FOUND THEN
        RETURN base_price;
    END IF;
    
    calculated_price := base_price;
    
    -- Adjust based on backlink value
    calculated_price := calculated_price + (site_data.backlink_value * 2);
    
    -- Adjust based on spam score (lower is better)
    calculated_price := calculated_price * (1 - (site_data.spam_score::NUMERIC / 200));
    
    -- Adjust based on domain authority
    IF site_data.domain_authority IS NOT NULL THEN
        calculated_price := calculated_price + (site_data.domain_authority * 0.5);
    END IF;
    
    -- Bonus for guest post detection
    IF site_data.guest_post_detected THEN
        calculated_price := calculated_price * 1.3;
    END IF;
    
    -- Category multiplier
    calculated_price := CASE site_data.category
        WHEN 'Finance' THEN calculated_price * 1.5
        WHEN 'Health' THEN calculated_price * 1.4
        WHEN 'SaaS' THEN calculated_price * 1.3
        WHEN 'Marketing' THEN calculated_price * 1.2
        ELSE calculated_price
    END;
    
    RETURN ROUND(calculated_price, 2);
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- SEED DATA (Optional - for testing)
-- ============================================

-- Insert sample categories for reference
COMMENT ON COLUMN gob_sites.category IS 'Categories: SaaS, Health, Finance, Marketing, Travel, Education, Technology, Other';

-- ============================================
-- GRANTS (Production deployment)
-- ============================================

-- Grant permissions to application user
-- GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO gob_app_user;
-- GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO gob_app_user;

-- ============================================
-- MIGRATION COMPLETE
-- ============================================

-- Verification query
SELECT 
    'gob_sites' as table_name, 
    COUNT(*) as row_count,
    pg_size_pretty(pg_total_relation_size('gob_sites')) as table_size
FROM gob_sites
UNION ALL
SELECT 
    'gob_orders', 
    COUNT(*),
    pg_size_pretty(pg_total_relation_size('gob_orders'))
FROM gob_orders
UNION ALL
SELECT 
    'gob_enrichment_queue', 
    COUNT(*),
    pg_size_pretty(pg_total_relation_size('gob_enrichment_queue'))
FROM gob_enrichment_queue;

-- Show indexes
SELECT 
    tablename,
    indexname,
    indexdef
FROM pg_indexes
WHERE tablename LIKE 'gob_%'
ORDER BY tablename, indexname;
