/**
 * Generated by Copilot per prompt: GO-AIBOB (GBOB) — GentleOmegaAI
 * 
 * server.js - Express API server for GO-AIBOB
 * 
 * Features:
 * - CORS configuration
 * - Rate limiting
 * - Request logging
 * - Error handling
 * - Authentication middleware
 * 
 * Usage: npm run gob:api
 */

import express from 'express';
import cors from 'cors';
import rateLimit from 'express-rate-limit';
import pino from 'pino';
import dotenv from 'dotenv';
import gobRoutes from './routes.js';
import { getDbPool } from '../db/postgres.js';

dotenv.config({ path: '.env.local' });

const app = express();
const port = process.env.PORT || 3001;

const logger = pino({
  level: process.env.LOG_LEVEL || 'info',
  transport: {
    target: 'pino-pretty',
    options: {
      colorize: true,
      translateTime: 'SYS:standard',
      ignore: 'pid,hostname'
    }
  }
});

// Middleware: CORS
app.use(cors({
  origin: process.env.FRONTEND_URL || 'http://localhost:5173',
  credentials: true
}));

// Middleware: JSON parsing
app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ extended: true, limit: '10mb' }));

// Middleware: Request logging
app.use((req, res, next) => {
  const start = Date.now();
  
  res.on('finish', () => {
    const duration = Date.now() - start;
    logger.info({
      method: req.method,
      url: req.url,
      status: res.statusCode,
      duration: `${duration}ms`,
      ip: req.ip
    });
  });
  
  next();
});

// Rate limiting for API endpoints
const apiLimiter = rateLimit({
  windowMs: parseInt(process.env.API_RATE_LIMIT_WINDOW_MS || '900000'), // 15 minutes
  max: parseInt(process.env.API_RATE_LIMIT_MAX_REQUESTS || '100'),
  message: {
    error: 'Too many requests, please try again later'
  },
  standardHeaders: true,
  legacyHeaders: false
});

// Stricter rate limit for enqueue endpoint
const enqueueLimiter = rateLimit({
  windowMs: 60000, // 1 minute
  max: 10, // 10 requests per minute
  message: {
    error: 'Too many URL submissions, please slow down'
  }
});

// Health check (no rate limit)
app.get('/health', (req, res) => {
  res.json({
    status: 'ok',
    service: 'GO-AIBOB API',
    timestamp: new Date().toISOString()
  });
});

// Apply rate limiting to API routes
app.use('/api/gob/enqueue', enqueueLimiter);
app.use('/api/gob', apiLimiter);

// Mount GO-AIBOB routes
app.use('/api/gob', gobRoutes);

// 404 handler
app.use((req, res) => {
  res.status(404).json({
    error: 'Not found',
    path: req.url
  });
});

// Error handler
app.use((err, req, res, next) => {
  logger.error('Unhandled error:', err);
  
  res.status(err.status || 500).json({
    error: err.message || 'Internal server error',
    ...(process.env.NODE_ENV === 'development' && { stack: err.stack })
  });
});

// Start server
async function startServer() {
  try {
    // Initialize database connection
    await getDbPool();
    logger.info('✅ Database connection established');

    // Start Express server
    app.listen(port, () => {
      logger.info(`🚀 GO-AIBOB API server running on port ${port}`);
      logger.info(`📡 Health check: http://localhost:${port}/health`);
      logger.info(`📚 API base: http://localhost:${port}/api/gob`);
      logger.info(`🌍 Environment: ${process.env.NODE_ENV || 'development'}`);
    });

  } catch (err) {
    logger.error('❌ Failed to start server:', err);
    process.exit(1);
  }
}

// Graceful shutdown
process.on('SIGTERM', () => {
  logger.info('🛑 SIGTERM received, shutting down gracefully');
  process.exit(0);
});

process.on('SIGINT', () => {
  logger.info('🛑 SIGINT received, shutting down gracefully');
  process.exit(0);
});

// Start if run directly
if (import.meta.url === `file://${process.argv[1]}`) {
  startServer();
}

export default app;
