/**
 * Generated by Copilot per prompt: GO-AIBOB (GBOB) — GentleOmegaAI
 * 
 * queue.js - HuggingFace enrichment queue management
 * 
 * Separate queue for HF enrichment to avoid blocking scraping
 */

import Queue from 'bull';
import pino from 'pino';
import dotenv from 'dotenv';
import { enrichSite } from './hf.js';
import { updateSiteEnrichment, getSiteById } from '../db/postgres.js';

dotenv.config({ path: '.env.local' });

const logger = pino({
  level: process.env.LOG_LEVEL || 'info',
  transport: {
    target: 'pino-pretty',
    options: { colorize: true }
  }
});

const enrichmentQueue = new Queue('gob-enrichment', process.env.REDIS_URL, {
  defaultJobOptions: {
    attempts: 2,
    backoff: {
      type: 'exponential',
      delay: 10000
    },
    removeOnComplete: 50,
    removeOnFail: 200
  }
});

/**
 * Enqueue a site for enrichment
 */
export async function enqueueEnrichment(siteId, siteData = null) {
  try {
    const job = await enrichmentQueue.add({
      siteId,
      siteData: siteData || null
    }, {
      priority: siteData?.guest_post_detected ? 1 : 5 // Prioritize guest post sites
    });

    logger.info(`✅ Enqueued enrichment job ${job.id} for site ${siteId}`);
    return job.id;
  } catch (err) {
    logger.error(`Failed to enqueue enrichment for site ${siteId}:`, err);
    throw err;
  }
}

/**
 * Process enrichment job
 */
async function processEnrichment(job) {
  const { siteId, siteData } = job.data;
  
  logger.info(`🤖 Processing enrichment for site ${siteId}`);

  try {
    // Fetch site data if not provided
    let site = siteData;
    if (!site) {
      site = await getSiteById(siteId);
      if (!site) {
        throw new Error(`Site ${siteId} not found`);
      }
    }

    // Run enrichment
    const enrichment = await enrichSite(site);

    // Save to database
    await updateSiteEnrichment(siteId, enrichment);

    logger.info(`✅ Enrichment completed for site ${siteId}`);
    
    return {
      siteId,
      enrichment,
      status: 'completed'
    };

  } catch (err) {
    logger.error(`❌ Enrichment failed for site ${siteId}:`, err);
    throw err;
  }
}

/**
 * Start enrichment worker
 */
export async function startEnrichmentWorker(concurrency = 2) {
  logger.info(`🤖 Starting enrichment worker with concurrency: ${concurrency}`);

  enrichmentQueue.process(concurrency, async (job) => {
    return await processEnrichment(job);
  });

  enrichmentQueue.on('completed', (job, result) => {
    logger.info(`✅ Enrichment job ${job.id} completed`);
  });

  enrichmentQueue.on('failed', (job, err) => {
    logger.error(`❌ Enrichment job ${job.id} failed:`, err.message);
  });

  logger.info('✅ Enrichment worker started');
}

export { enrichmentQueue };
