/**
 * Generated by Copilot per prompt: GO-AIBOB (GBOB) — GentleOmegaAI
 * 
 * pageFunction.js - In-page extraction logic for Puppeteer
 * 
 * Purpose: Runs inside the browser context to extract:
 * - URL, canonical, title, h1, meta description
 * - Emails (defensive regex + fallback)
 * - Links (sample + counts)
 * - First paragraph for preview
 * - HTML snapshot (truncated to 200k chars)
 * 
 * Safety: Uses try-catch everywhere, returns standardized JSON
 */

function pageFunction() {
  const MAX_HTML_LENGTH = 200000; // 200k chars to save cost
  const MAX_LINKS_SAMPLE = 50;
  const MAX_EMAILS = 20;

  const result = {
    url: window.location.href,
    canonical: null,
    title: null,
    h1: null,
    metaDesc: null,
    emails: [],
    links_sample: [],
    links_count: 0,
    internal_links_count: 0,
    external_links_count: 0,
    firstParagraph: null,
    htmlSnapshot: null,
    extractedAt: new Date().toISOString(),
    errors: []
  };

  // Helper: Safe text extraction
  const getText = (selector, element = document) => {
    try {
      const el = element.querySelector(selector);
      return el ? el.textContent.trim() : null;
    } catch (err) {
      result.errors.push(`getText(${selector}): ${err.message}`);
      return null;
    }
  };

  // Helper: Safe attribute extraction
  const getAttr = (selector, attr, element = document) => {
    try {
      const el = element.querySelector(selector);
      return el ? el.getAttribute(attr) : null;
    } catch (err) {
      result.errors.push(`getAttr(${selector}, ${attr}): ${err.message}`);
      return null;
    }
  };

  // Helper: Email regex (defensive - avoids false positives)
  const emailRegex = /\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b/g;

  // Helper: Extract unique emails from text
  const extractEmails = (text) => {
    if (!text) return [];
    const matches = text.match(emailRegex) || [];
    // Filter out common false positives
    return [...new Set(matches)]
      .filter(email => 
        !email.endsWith('.png') && 
        !email.endsWith('.jpg') && 
        !email.endsWith('.gif') &&
        !email.includes('example.com') &&
        !email.includes('test.com') &&
        !email.includes('sentry.io') // Common tracking domain
      )
      .slice(0, MAX_EMAILS);
  };

  // 1. Extract canonical URL
  try {
    result.canonical = 
      getAttr('link[rel="canonical"]', 'href') ||
      getAttr('meta[property="og:url"]', 'content') ||
      result.url;
  } catch (err) {
    result.errors.push(`Canonical extraction: ${err.message}`);
  }

  // 2. Extract title
  try {
    result.title = 
      document.title ||
      getText('title') ||
      getAttr('meta[property="og:title"]', 'content') ||
      getText('h1');
  } catch (err) {
    result.errors.push(`Title extraction: ${err.message}`);
  }

  // 3. Extract h1
  try {
    result.h1 = getText('h1') || getText('h2');
  } catch (err) {
    result.errors.push(`H1 extraction: ${err.message}`);
  }

  // 4. Extract meta description
  try {
    result.metaDesc = 
      getAttr('meta[name="description"]', 'content') ||
      getAttr('meta[property="og:description"]', 'content') ||
      getAttr('meta[name="twitter:description"]', 'content');
  } catch (err) {
    result.errors.push(`Meta description extraction: ${err.message}`);
  }

  // 5. Extract first paragraph
  try {
    const paragraphs = document.querySelectorAll('p');
    for (let p of paragraphs) {
      const text = p.textContent.trim();
      if (text.length > 50) { // Skip short/empty paragraphs
        result.firstParagraph = text.substring(0, 500); // Max 500 chars
        break;
      }
    }
  } catch (err) {
    result.errors.push(`First paragraph extraction: ${err.message}`);
  }

  // 6. Extract emails
  try {
    // Strategy 1: Search in common contact selectors
    const contactSelectors = [
      'a[href^="mailto:"]',
      '.contact',
      '#contact',
      '.email',
      'footer',
      '[class*="contact"]',
      '[id*="contact"]'
    ];

    let emailText = '';
    contactSelectors.forEach(selector => {
      try {
        const elements = document.querySelectorAll(selector);
        elements.forEach(el => {
          if (el.href && el.href.startsWith('mailto:')) {
            const email = el.href.replace('mailto:', '').split('?')[0];
            if (email && email.includes('@')) {
              result.emails.push(email);
            }
          }
          emailText += ' ' + el.textContent;
        });
      } catch (e) {
        // Skip selector if fails
      }
    });

    // Strategy 2: Scan entire body text (fallback)
    if (result.emails.length === 0) {
      emailText += ' ' + document.body.innerText;
    }

    // Extract and deduplicate
    const extractedEmails = extractEmails(emailText);
    result.emails = [...new Set([...result.emails, ...extractedEmails])].slice(0, MAX_EMAILS);

  } catch (err) {
    result.errors.push(`Email extraction: ${err.message}`);
  }

  // 7. Extract links
  try {
    const currentDomain = new URL(window.location.href).hostname.replace(/^www\./, '');
    const allLinks = document.querySelectorAll('a[href]');
    const linkMap = new Map(); // Deduplicate by href
    
    allLinks.forEach((link) => {
      try {
        const href = link.href;
        if (!href || href.startsWith('javascript:') || href.startsWith('#')) return;
        
        const linkUrl = new URL(href);
        const linkDomain = linkUrl.hostname.replace(/^www\./, '');
        const isInternal = linkDomain === currentDomain;
        
        if (isInternal) {
          result.internal_links_count++;
        } else {
          result.external_links_count++;
        }
        
        // Store sample
        if (linkMap.size < MAX_LINKS_SAMPLE) {
          linkMap.set(href, {
            url: href,
            text: link.textContent.trim().substring(0, 100),
            isInternal,
            rel: link.rel || null,
            target: link.target || null
          });
        }
      } catch (e) {
        // Skip invalid URLs
      }
    });

    result.links_count = allLinks.length;
    result.links_sample = Array.from(linkMap.values());

  } catch (err) {
    result.errors.push(`Link extraction: ${err.message}`);
  }

  // 8. Extract HTML snapshot
  try {
    const fullHtml = document.documentElement.outerHTML;
    result.htmlSnapshot = fullHtml.substring(0, MAX_HTML_LENGTH);
    
    if (fullHtml.length > MAX_HTML_LENGTH) {
      result.htmlSnapshot += '\n\n<!-- TRUNCATED: Original length was ' + fullHtml.length + ' chars -->';
    }
  } catch (err) {
    result.errors.push(`HTML snapshot extraction: ${err.message}`);
    result.htmlSnapshot = '<html><body>Extraction failed</body></html>';
  }

  // 9. Additional metadata
  try {
    result.meta = {
      hasContactPage: !!(
        document.querySelector('a[href*="contact"]') ||
        document.querySelector('[href*="contact-us"]')
      ),
      hasAboutPage: !!(
        document.querySelector('a[href*="about"]') ||
        document.querySelector('[href*="about-us"]')
      ),
      hasBlog: !!(
        document.querySelector('a[href*="blog"]') ||
        document.querySelector('[href*="/blog/"]')
      ),
      socialLinks: {
        facebook: !!document.querySelector('a[href*="facebook.com"]'),
        twitter: !!document.querySelector('a[href*="twitter.com"]') || !!document.querySelector('a[href*="x.com"]'),
        linkedin: !!document.querySelector('a[href*="linkedin.com"]'),
        instagram: !!document.querySelector('a[href*="instagram.com"]')
      }
    };
  } catch (err) {
    result.errors.push(`Metadata extraction: ${err.message}`);
  }

  // 10. Guest post detection keywords
  try {
    const bodyText = document.body.innerText.toLowerCase();
    const guestPostKeywords = [
      'write for us',
      'guest post',
      'submit guest',
      'contribute',
      'contributor guidelines',
      'become a contributor',
      'submit article',
      'guest author',
      'guest blogging'
    ];

    result.guestPostKeywords = guestPostKeywords.filter(keyword => 
      bodyText.includes(keyword)
    );
    
    result.hasGuestPostIndicators = result.guestPostKeywords.length > 0;
  } catch (err) {
    result.errors.push(`Guest post detection: ${err.message}`);
  }

  return result;
}

// Export for Node.js testing
if (typeof module !== 'undefined' && module.exports) {
  module.exports = pageFunction;
}
