import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';

interface ReportOptions {
    title: string;
    subtitle?: string;
    brandName?: string; // For white-labeling
    userName?: string;
    includeTimestamp?: boolean;
}

export const generatePDFReport = (
    options: ReportOptions,
    tables: Array<{ title: string; head: any[]; body: any[] }>,
    charts?: any // Placeholder for chart image data if we implement chart capture later
) => {
    const doc = new jsPDF();
    const BRAND_COLOR = '#00f7ff'; // Cyan brand color
    const TEXT_COLOR = '#333333';

    // -- Header --
    const drawHeader = () => {
        // Brand Stripe
        doc.setFillColor(0, 0, 0); // Black background
        doc.rect(0, 0, doc.internal.pageSize.width, 20, 'F');

        doc.setTextColor(255, 255, 255);
        doc.setFontSize(16);
        doc.setFont('helvetica', 'bold');
        // Use custom brand name if provided (White Label), else default
        doc.text(options.brandName || 'GentleΩmega AI', 14, 13);

        // Date
        if (options.includeTimestamp !== false) {
            doc.setFontSize(10);
            doc.setFont('helvetica', 'normal');
            doc.text(format(new Date(), 'PPpp'), doc.internal.pageSize.width - 14, 13, { align: 'right' });
        }
    };

    drawHeader();

    // -- Content Title --
    let currentY = 35;
    doc.setTextColor(TEXT_COLOR);
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text(options.title, 14, currentY);

    if (options.subtitle) {
        currentY += 8;
        doc.setFontSize(12);
        doc.setTextColor(100, 100, 100);
        doc.setFont('helvetica', 'normal');
        doc.text(options.subtitle, 14, currentY);
    }

    if (options.userName) {
        currentY += 6;
        doc.setFontSize(10);
        doc.text(`Prepared for: ${options.userName}`, 14, currentY);
    }

    currentY += 10;

    // -- Divider --
    doc.setDrawColor(200, 200, 200);
    doc.line(14, currentY, doc.internal.pageSize.width - 14, currentY);
    currentY += 10;

    // -- Tables --
    tables.forEach((table) => {
        // Table Title
        if ((currentY + 15) > doc.internal.pageSize.height) {
            doc.addPage();
            drawHeader();
            currentY = 35;
        }

        doc.setFontSize(14);
        doc.setTextColor(0, 0, 0);
        doc.setFont('helvetica', 'bold');
        doc.text(table.title, 14, currentY);
        currentY += 5;

        autoTable(doc, {
            startY: currentY,
            head: table.head,
            body: table.body,
            theme: 'grid',
            headStyles: { fillColor: [0, 0, 0], textColor: [0, 247, 255], fontStyle: 'bold' }, // Black with Cyan text
            styles: { fontSize: 9, cellPadding: 3 },
            alternateRowStyles: { fillColor: [245, 245, 245] },
            margin: { top: 30 },
            didDrawPage: (data) => {
                // Redraw header on new pages
                if (data.pageNumber > 1) drawHeader();
            }
        });

        // Update Y for next element (autotable state)
        currentY = (doc as any).lastAutoTable.finalY + 15;
    });

    // -- Footer --
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);

        // Footer Line
        doc.setDrawColor(230, 230, 230);
        doc.line(14, doc.internal.pageSize.height - 15, doc.internal.pageSize.width - 14, doc.internal.pageSize.height - 15);

        const footerText = options.brandName
            ? `Generated by ${options.brandName} Reporting Engine`
            : 'Powered by GentleΩmega AI Ecosystem';

        doc.text(footerText, 14, doc.internal.pageSize.height - 8);
        doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.width - 14, doc.internal.pageSize.height - 8, { align: 'right' });
    }

    // Save
    const fileName = `${options.title.replace(/\s+/g, '_').toLowerCase()}_${format(new Date(), 'yyyyMMdd')}.pdf`;
    doc.save(fileName);
};
