/**
 * Generated by Copilot per prompt: GO-AIBOB (GBOB) — GentleOmegaAI
 * 
 * scoring.js - Spam detection and backlink value calculation
 * 
 * Purpose: Provides heuristic-based scoring without external paid APIs
 * - spam_score: 0-100 (0 = clean, 100 = definite spam)
 * - backlink_value: $0-$500+ (estimated value for backlink placement)
 * 
 * Factors considered:
 * - Email presence
 * - Link patterns (internal vs external ratio)
 * - Content quality indicators
 * - Domain characteristics
 * - Social presence
 * - Guest post indicators
 * 
 * TODO: Integrate with Moz/Ahrefs API for domain authority (paid)
 */

/**
 * Calculate spam score (0-100, lower is better)
 * @param {Object} siteData - Scraped site data from pageFunction
 * @returns {number} Spam score 0-100
 */
function calculateSpamScore(siteData) {
  let spamScore = 0;
  const {
    title,
    metaDesc,
    emails,
    links_count,
    internal_links_count,
    external_links_count,
    links_sample,
    firstParagraph,
    htmlSnapshot,
    url,
    meta,
    guestPostKeywords = []
  } = siteData;

  // 1. Missing essential metadata (+20 spam points)
  if (!title || title.length < 10) spamScore += 10;
  if (!metaDesc || metaDesc.length < 30) spamScore += 10;

  // 2. Suspicious link patterns
  const totalLinks = links_count || 0;
  const externalLinks = external_links_count || 0;
  const internalLinks = internal_links_count || 0;

  if (totalLinks > 0) {
    const externalRatio = externalLinks / totalLinks;
    
    // Too many external links (>70%) suggests spam/link farm
    if (externalRatio > 0.7) spamScore += 15;
    
    // Too few internal links suggests thin content
    if (internalLinks < 3 && totalLinks > 10) spamScore += 10;
  }

  // 3. Suspicious link text patterns
  if (links_sample && links_sample.length > 0) {
    const spamKeywords = ['viagra', 'cialis', 'casino', 'poker', 'porn', 'xxx', 'betting'];
    const hasSpamLinks = links_sample.some(link => 
      spamKeywords.some(keyword => 
        (link.text || '').toLowerCase().includes(keyword) ||
        (link.url || '').toLowerCase().includes(keyword)
      )
    );
    if (hasSpamLinks) spamScore += 30;
  }

  // 4. Low-quality content indicators
  if (firstParagraph) {
    const wordCount = firstParagraph.split(/\s+/).length;
    if (wordCount < 20) spamScore += 10; // Very thin content
    
    // Check for keyword stuffing (repeated words)
    const words = firstParagraph.toLowerCase().split(/\s+/);
    const wordFreq = {};
    words.forEach(word => {
      if (word.length > 3) {
        wordFreq[word] = (wordFreq[word] || 0) + 1;
      }
    });
    
    const maxFreq = Math.max(...Object.values(wordFreq));
    if (maxFreq > words.length * 0.1) spamScore += 15; // Keyword stuffing
  }

  // 5. Suspicious TLD
  const suspiciousTLDs = ['.tk', '.ml', '.ga', '.cf', '.gq', '.xyz', '.top', '.club'];
  const hasSuspiciousTLD = suspiciousTLDs.some(tld => url.includes(tld));
  if (hasSuspiciousTLD) spamScore += 15;

  // 6. Positive signals (reduce spam score)
  if (emails && emails.length > 0) spamScore -= 5; // Has contact info
  if (meta && meta.hasContactPage) spamScore -= 5;
  if (meta && meta.hasAboutPage) spamScore -= 5;
  if (meta && Object.values(meta.socialLinks || {}).some(v => v)) spamScore -= 5;

  // 7. Guest post opportunity is a positive signal
  if (guestPostKeywords.length > 0) spamScore -= 10;

  // Clamp to 0-100 range
  return Math.max(0, Math.min(100, spamScore));
}

/**
 * Calculate backlink value in USD (estimated price)
 * @param {Object} siteData - Scraped site data
 * @param {number} spamScore - Pre-calculated spam score
 * @param {Object} enrichment - HuggingFace enrichment data (optional)
 * @returns {number} Estimated backlink value in USD
 */
function calculateBacklinkValue(siteData, spamScore, enrichment = {}) {
  const {
    emails,
    links_count,
    internal_links_count,
    meta,
    guestPostKeywords = [],
    url
  } = siteData;

  let baseValue = 20.00; // Base price for any site

  // 1. Spam penalty (major factor)
  if (spamScore < 20) {
    baseValue *= 3.0; // Clean sites are worth 3x more
  } else if (spamScore < 40) {
    baseValue *= 2.0;
  } else if (spamScore < 60) {
    baseValue *= 1.2;
  } else {
    baseValue *= 0.3; // High spam sites are worth much less
  }

  // 2. Contact information bonus
  if (emails && emails.length > 0) {
    baseValue *= 1.5; // 50% bonus for having contact info
  }

  // 3. Link structure quality
  if (internal_links_count > 20) {
    baseValue *= 1.3; // Well-structured site
  }

  // 4. Social presence bonus
  if (meta && meta.socialLinks) {
    const socialCount = Object.values(meta.socialLinks).filter(v => v).length;
    baseValue *= (1 + socialCount * 0.1); // 10% per social platform
  }

  // 5. Guest post indicators (major bonus)
  if (guestPostKeywords.length > 0) {
    baseValue *= 2.0; // 100% bonus for explicit guest post opportunities
  }

  // 6. Category multiplier (from HuggingFace enrichment)
  if (enrichment.category) {
    const categoryMultipliers = {
      'Finance': 2.0,
      'Health': 1.8,
      'SaaS': 1.7,
      'Technology': 1.5,
      'Marketing': 1.4,
      'Education': 1.3,
      'Travel': 1.2,
      'Other': 1.0
    };
    baseValue *= (categoryMultipliers[enrichment.category] || 1.0);
  }

  // 7. Domain authority estimate (heuristic based on available data)
  // TODO: Replace with actual Moz/Ahrefs API when available
  let estimatedDA = 20; // Default low DA
  
  if (meta) {
    if (meta.hasBlog) estimatedDA += 10;
    if (meta.hasAboutPage && meta.hasContactPage) estimatedDA += 10;
    if (internal_links_count > 50) estimatedDA += 10;
  }
  
  // DA bonus: 1% per DA point above 20
  if (estimatedDA > 20) {
    baseValue *= (1 + (estimatedDA - 20) * 0.01);
  }

  // 8. TLD quality bonus
  const premiumTLDs = ['.com', '.org', '.edu', '.gov'];
  const hasPremiumTLD = premiumTLDs.some(tld => url.endsWith(tld));
  if (hasPremiumTLD) {
    baseValue *= 1.2;
  }

  // Round to 2 decimal places
  return Math.round(baseValue * 100) / 100;
}

/**
 * Calculate domain authority estimate (heuristic, 0-100)
 * @param {Object} siteData - Scraped site data
 * @returns {number} Estimated domain authority 0-100
 */
function estimateDomainAuthority(siteData) {
  const {
    links_count,
    internal_links_count,
    external_links_count,
    meta,
    emails
  } = siteData;

  let da = 10; // Base DA for any site

  // Internal link structure
  if (internal_links_count > 100) da += 20;
  else if (internal_links_count > 50) da += 15;
  else if (internal_links_count > 20) da += 10;

  // Content indicators
  if (meta) {
    if (meta.hasBlog) da += 10;
    if (meta.hasAboutPage) da += 5;
    if (meta.hasContactPage) da += 5;
    
    const socialCount = Object.values(meta.socialLinks || {}).filter(v => v).length;
    da += socialCount * 3; // 3 points per social platform
  }

  // Contact information
  if (emails && emails.length > 0) da += 5;

  // External links (reasonable amount suggests authority)
  if (external_links_count > 10 && external_links_count < 50) da += 5;

  return Math.min(100, da);
}

/**
 * Comprehensive scoring function
 * @param {Object} siteData - Scraped site data
 * @param {Object} enrichment - Optional HuggingFace enrichment
 * @returns {Object} Complete scoring results
 */
function scoreSite(siteData, enrichment = {}) {
  const spamScore = calculateSpamScore(siteData);
  const domainAuthority = estimateDomainAuthority(siteData);
  const backlinkValue = calculateBacklinkValue(siteData, spamScore, enrichment);
  
  return {
    spam_score: spamScore,
    domain_authority: domainAuthority,
    backlink_value: backlinkValue,
    guest_post_detected: (siteData.guestPostKeywords || []).length > 0,
    quality_tier: getQualityTier(spamScore, backlinkValue),
    scoring_version: '1.0.0',
    scored_at: new Date().toISOString()
  };
}

/**
 * Get quality tier classification
 * @param {number} spamScore 
 * @param {number} backlinkValue 
 * @returns {string} Quality tier
 */
function getQualityTier(spamScore, backlinkValue) {
  if (spamScore < 20 && backlinkValue > 100) return 'Premium';
  if (spamScore < 30 && backlinkValue > 50) return 'High';
  if (spamScore < 50 && backlinkValue > 25) return 'Medium';
  if (spamScore < 70) return 'Low';
  return 'Spam';
}

export {
  calculateSpamScore,
  calculateBacklinkValue,
  estimateDomainAuthority,
  scoreSite,
  getQualityTier
};

