/**
 * Generated by Copilot per prompt: GO-AIBOB (GBOB) — GentleOmegaAI
 * 
 * postgres.js - Database connection and query helpers
 * 
 * Features:
 * - Connection pooling for performance
 * - Prepared statements for security
 * - Retry logic for resilience
 * - Query logging for debugging
 */

import pg from 'pg';
import pino from 'pino';
import dotenv from 'dotenv';

dotenv.config({ path: '.env.local' });

const { Pool } = pg;

const logger = pino({
  level: process.env.LOG_LEVEL || 'info',
  transport: {
    target: 'pino-pretty',
    options: { colorize: true }
  }
});

// Database connection pool
let pool = null;

/**
 * Get or create database connection pool
 */
export function getDbPool() {
  if (pool) return pool;

  const connectionString = process.env.POSTGRES_URL;

  if (!connectionString) {
    throw new Error('POSTGRES_URL not configured in .env.local');
  }

  pool = new Pool({
    connectionString,
    max: 20, // Maximum pool size
    idleTimeoutMillis: 30000,
    connectionTimeoutMillis: 10000,
    ssl: process.env.NODE_ENV === 'production' ? { rejectUnauthorized: false } : false
  });

  pool.on('error', (err) => {
    logger.error('Unexpected database error:', err);
  });

  logger.info('✅ Database pool initialized');
  return pool;
}

/**
 * Insert scraped site data
 */
export async function insertScrapedSite(siteData) {
  const db = getDbPool();

  const query = `
    INSERT INTO gob_sites (
      url, canonical, title, h1, meta_description, first_paragraph,
      emails, phone_numbers, links_count, links_sample,
      internal_links_count, external_links_count,
      html_snapshot, html_length,
      spam_score, backlink_value, domain_authority, guest_post_detected,
      category, status, scraped_at, created_at, updated_at
    ) VALUES (
      $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14,
      $15, $16, $17, $18, $19, $20, $21, NOW(), NOW()
    )
    ON CONFLICT (url) DO UPDATE SET
      canonical = EXCLUDED.canonical,
      title = EXCLUDED.title,
      h1 = EXCLUDED.h1,
      meta_description = EXCLUDED.meta_description,
      first_paragraph = EXCLUDED.first_paragraph,
      emails = EXCLUDED.emails,
      links_count = EXCLUDED.links_count,
      links_sample = EXCLUDED.links_sample,
      internal_links_count = EXCLUDED.internal_links_count,
      external_links_count = EXCLUDED.external_links_count,
      html_snapshot = EXCLUDED.html_snapshot,
      html_length = EXCLUDED.html_length,
      spam_score = EXCLUDED.spam_score,
      backlink_value = EXCLUDED.backlink_value,
      domain_authority = EXCLUDED.domain_authority,
      guest_post_detected = EXCLUDED.guest_post_detected,
      status = EXCLUDED.status,
      scraped_at = EXCLUDED.scraped_at,
      updated_at = NOW()
    RETURNING id
  `;

  const values = [
    siteData.url,
    siteData.canonical,
    siteData.title,
    siteData.h1,
    siteData.metaDesc,
    siteData.firstParagraph,
    JSON.stringify(siteData.emails || []),
    JSON.stringify([]), // phone_numbers (future enhancement)
    siteData.links_count || 0,
    JSON.stringify(siteData.links_sample || []),
    siteData.internal_links_count || 0,
    siteData.external_links_count || 0,
    siteData.htmlSnapshot,
    siteData.htmlSnapshot?.length || 0,
    siteData.spam_score || 0,
    siteData.backlink_value || 0,
    siteData.domain_authority || 0,
    siteData.guest_post_detected || false,
    siteData.category || 'Other',
    siteData.status || 'scraped',
    siteData.scraped_at || new Date()
  ];

  try {
    const result = await db.query(query, values);
    return result.rows[0].id;
  } catch (err) {
    logger.error('Database insert failed:', err);
    throw err;
  }
}

/**
 * Update site status
 */
export async function updateSiteStatus(url, status, errorMessage = null) {
  const db = getDbPool();

  const query = `
    UPDATE gob_sites
    SET status = $2, error_message = $3, updated_at = NOW()
    WHERE url = $1
  `;

  try {
    await db.query(query, [url, status, errorMessage]);
  } catch (err) {
    logger.error('Status update failed:', err);
    throw err;
  }
}

/**
 * Get site by ID
 */
export async function getSiteById(siteId) {
  const db = getDbPool();
  const result = await db.query('SELECT * FROM gob_sites WHERE id = $1', [siteId]);
  return result.rows[0] || null;
}

/**
 * Get site by URL
 */
export async function getSiteByUrl(url) {
  const db = getDbPool();
  const result = await db.query('SELECT * FROM gob_sites WHERE url = $1', [url]);
  return result.rows[0] || null;
}

/**
 * List sites with filters and pagination
 */
export async function listSites(filters = {}, page = 1, limit = 20) {
  const db = getDbPool();
  const offset = (page - 1) * limit;

  let whereClauses = [];
  let values = [];
  let paramIndex = 1;

  // Build WHERE clause dynamically
  if (filters.status) {
    whereClauses.push(`status = $${paramIndex++}`);
    values.push(filters.status);
  }

  if (filters.category) {
    whereClauses.push(`category = $${paramIndex++}`);
    values.push(filters.category);
  }

  if (filters.hasEmail) {
    whereClauses.push(`jsonb_array_length(emails) > 0`);
  }

  if (filters.minBacklinkValue) {
    whereClauses.push(`backlink_value >= $${paramIndex++}`);
    values.push(filters.minBacklinkValue);
  }

  if (filters.maxSpamScore) {
    whereClauses.push(`spam_score <= $${paramIndex++}`);
    values.push(filters.maxSpamScore);
  }

  if (filters.guestPostOnly) {
    whereClauses.push(`guest_post_detected = true`);
  }

  const whereClause = whereClauses.length > 0 ? `WHERE ${whereClauses.join(' AND ')}` : '';

  // Count query
  const countQuery = `SELECT COUNT(*) as total FROM gob_sites ${whereClause}`;
  const countResult = await db.query(countQuery, values);
  const total = parseInt(countResult.rows[0].total);

  // Data query
  values.push(limit, offset);
  const dataQuery = `
    SELECT 
      id, url, domain, title, category,
      jsonb_array_length(emails) as email_count,
      links_count, spam_score, backlink_value,
      guest_post_detected, status, scraped_at, updated_at
    FROM gob_sites
    ${whereClause}
    ORDER BY backlink_value DESC, spam_score ASC
    LIMIT $${paramIndex++} OFFSET $${paramIndex++}
  `;

  const dataResult = await db.query(dataQuery, values);

  return {
    data: dataResult.rows,
    total,
    page,
    limit,
    totalPages: Math.ceil(total / limit)
  };
}

/**
 * Update site with HF enrichment
 */
export async function updateSiteEnrichment(siteId, enrichmentData) {
  const db = getDbPool();

  const query = `
    UPDATE gob_sites
    SET 
      category = $2,
      language = $3,
      summary = $4,
      hf_enrichment = $5,
      hf_enriched_at = NOW(),
      status = 'enriched',
      updated_at = NOW()
    WHERE id = $1
  `;

  const values = [
    siteId,
    enrichmentData.category || 'Other',
    enrichmentData.language || 'unknown',
    enrichmentData.summary || null,
    JSON.stringify(enrichmentData)
  ];

  try {
    await db.query(query, values);
  } catch (err) {
    logger.error('Enrichment update failed:', err);
    throw err;
  }
}

/**
 * Create backlink order
 */
export async function createOrder(orderData) {
  const db = getDbPool();

  const invoiceId = `INV-${Date.now()}-${Math.floor(Math.random() * 10000)}`;

  const query = `
    INSERT INTO gob_orders (
      site_id, site_url, buyer_name, buyer_email, buyer_phone,
      keywords, content_type, target_url,
      price_estimate, currency, status, invoice_id,
      notes, created_at, updated_at
    ) VALUES (
      $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, NOW(), NOW()
    )
    RETURNING id, invoice_id
  `;

  const values = [
    orderData.site_id,
    orderData.site_url,
    orderData.buyer_name,
    orderData.buyer_email,
    orderData.buyer_phone || null,
    orderData.keywords || [],
    orderData.content_type || 'guest_post',
    orderData.target_url,
    orderData.price_estimate,
    orderData.currency || 'USD',
    'pending',
    invoiceId,
    orderData.notes || null
  ];

  try {
    const result = await db.query(query, values);
    return result.rows[0];
  } catch (err) {
    logger.error('Order creation failed:', err);
    throw err;
  }
}

/**
 * Export sites to CSV format
 */
export async function exportSitesToCSV(filters = {}) {
  const sites = await listSites(filters, 1, 10000); // Export up to 10k sites
  
  const headers = ['ID', 'URL', 'Domain', 'Title', 'Category', 'Emails', 'Links', 'Spam Score', 'Backlink Value', 'Status'];
  const rows = sites.data.map(site => [
    site.id,
    site.url,
    site.domain,
    site.title,
    site.category,
    site.email_count,
    site.links_count,
    site.spam_score,
    site.backlink_value,
    site.status
  ]);

  return { headers, rows };
}

/**
 * Health check
 */
export async function healthCheck() {
  try {
    const db = getDbPool();
    await db.query('SELECT 1');
    return { status: 'ok', database: 'connected' };
  } catch (err) {
    return { status: 'error', database: 'disconnected', error: err.message };
  }
}
